import pandas as pd
from sklearn.linear_model import LinearRegression
print("Задача 1")
print("Возьмите данные из задания и закиньте их в файл 'report.csv'\n")
df = pd.read_csv("report.csv", index_col='id')

X = pd.DataFrame(df.drop(['Y'], axis=1))
Y = pd.DataFrame(df['Y'])
reg = LinearRegression().fit(X,Y)
print("Задача 2")
print("Введите название первой конфеты, с пробелами")
s = input()
print("Введите название второй конфеты, также с пробелами)")
s1 = input()
df2 = pd.read_csv("candy-data.csv", index_col='competitorname')
train_data = df2.drop([s, s1])
X2 = pd.DataFrame(train_data.drop(['winpercent', 'Y'], axis=1))
Y2 = pd.DataFrame(train_data['winpercent'])
reg2 = LinearRegression().fit(X2, Y2)
candy1 = df2.loc[s,:].to_frame().T
candy2 = df2.loc[s1,:].to_frame().T
print("\nОтветы")
print(f'Первый ответ -> {round(float(df["X"].mean()), 3)}')
print(f'Второй ответ -> {round(float(df["Y"].mean()), 3)}')
print(f'Третий ответ -> {round(float(reg.coef_), 3)}')
print(f'Четвертый ответ -> {round(float(reg.intercept_), 3)}')
print(f'Пятый ответ -> {round(float(reg.score(X,Y)), 3)}')
print("Шестой ответ -> " + str(round(float(*reg2.predict(candy1.drop(['winpercent', 'Y'], axis=1))), 3)))
print("Седьмой ответ -> " + str(round(float(*reg2.predict(candy2.drop(['winpercent', 'Y'], axis=1))), 3)))
print(f'Восьмой ответ -> {round(float(reg2.predict([[0, 1, 1, 1, 0, 0, 1, 0, 0, 0.32, 0.219]])), 3)}')
print("На ошибку в конце можно забить)")